export const RestaurantList = [
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '349727',
			name: 'Paris Panini - Gourmet Sandwiches & Wraps',
			uuid: '8a4b4743-11e8-41ff-84af-9b45670ed9c3',
			city: '1',
			area: 'Sanjay Nagar',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'h2d9das6my0ujek77zhf',
			cuisines: ['Continental', 'Pastas', 'Salads', 'Snacks', 'Desserts', 'Fast Food', 'French'],
			tags: [],
			costForTwo: 50000,
			costForTwoString: '₹500 FOR TWO',
			deliveryTime: 24,
			minDeliveryTime: 24,
			maxDeliveryTime: 24,
			slaString: '24 MINS',
			lastMileTravel: 2,
			slugs: {
				restaurant: 'paris-panini-sanjay-nagar,-new-bel-road-sanjay-nagar,-new-bel-road',
				city: 'bangalore',
			},
			cityState: '1',
			address: '#269, RMV 2ND STAGE, 2ND BLOCK, ARAMANE NAGAR, BANGALORE, Yeshwanthapura , B.B.M.P North, Karnataka-560094',
			locality: 'New BEL Road',
			parentId: 21019,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2700,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2700,
				message: '',
				title: 'Delivery Charge',
				amount: '2700',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=7138169~p=1~eid=00000188-c912-02ab-0edf-ceec003d0123',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '30% OFF',
				subHeader: 'UPTO ₹75',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '349727',
				deliveryTime: 24,
				minDeliveryTime: 24,
				maxDeliveryTime: 24,
				lastMileTravel: 2,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.4',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '265272',
			name: 'Hotel Empire',
			uuid: '21997aeb-f049-4c7c-878a-f1ca69c80a68',
			city: '1',
			area: 'New BEL Road',
			totalRatingsString: '10000+ ratings',
			cloudinaryImageId: 'c2nxvhpqcsxtnlb7wxwq',
			cuisines: ['North Indian', 'Kebabs', 'Biryani'],
			tags: [],
			costForTwo: 80000,
			costForTwoString: '₹800 FOR TWO',
			deliveryTime: 20,
			minDeliveryTime: 20,
			maxDeliveryTime: 20,
			slaString: '20 MINS',
			lastMileTravel: 1,
			slugs: {
				restaurant: 'hotel-empire-sanjay-nagar,-new-bel-road-sanjay-nagar,-new-bel-road',
				city: 'bangalore',
			},
			cityState: '1',
			address: '2ND,3RD FLOOR MUNICIPAL NO:193,M H CHANDRAPPA,NEAR GOWRI APARTMENTS,NEW BEL ROAD,MATHIKERE,BANGALORE,B.B.M.P North,560054',
			locality: 'Mathikere',
			parentId: 475,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2700,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2700,
				message: '',
				title: 'Delivery Charge',
				amount: '2700',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '10% OFF',
				subHeader: 'UPTO ₹40',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '265272',
				deliveryTime: 20,
				minDeliveryTime: 20,
				maxDeliveryTime: 20,
				lastMileTravel: 1,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '4.1',
			totalRatings: 10000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '8032',
			name: 'Burger King',
			uuid: '37ef8766-1c4d-4aed-a50e-ce18489c27c5',
			city: '1',
			area: 'Sanjaynagar',
			totalRatingsString: '10000+ ratings',
			cloudinaryImageId: 'e33e1d3ba7d6b2bb0d45e1001b731fcf',
			cuisines: ['Burgers', 'American'],
			tags: [],
			costForTwo: 35000,
			costForTwoString: '₹350 FOR TWO',
			deliveryTime: 23,
			minDeliveryTime: 23,
			maxDeliveryTime: 23,
			slaString: '23 MINS',
			lastMileTravel: 1.600000023841858,
			slugs: {
				restaurant: 'burger-king-rmv-2nd-stage-sanjay-nagar-new-bel-road-yeshwanthpur',
				city: 'bangalore',
			},
			cityState: '1',
			address: 'No.48 , Casino Tower , Opp Ms. Ramaiah Hospital , New Bell Road,RMV 2nd Stage ,Deva Sandra ,Bangalore -560054.',
			locality: 'RMV 2nd Stage',
			parentId: 166,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2700,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2700,
				message: '',
				title: 'Delivery Charge',
				amount: '2700',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1.6 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹120',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '8032',
				deliveryTime: 23,
				minDeliveryTime: 23,
				maxDeliveryTime: 23,
				lastMileTravel: 1.600000023841858,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '4.0',
			totalRatings: 10000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '41924',
			name: 'California Burrito',
			uuid: '723f9095-6fa4-4395-be34-88b1c9ec1084',
			city: '1',
			area: 'Malleshwaram',
			totalRatingsString: '5000+ ratings',
			cloudinaryImageId: 'hhhmqpgnmvow7iyzlsdc',
			cuisines: ['Mexican', 'American', 'Salads', 'Continental', 'Keto', 'Healthy Food'],
			tags: [],
			costForTwo: 25000,
			costForTwoString: '₹250 FOR TWO',
			deliveryTime: 39,
			minDeliveryTime: 39,
			maxDeliveryTime: 39,
			slaString: '39 MINS',
			lastMileTravel: 4.400000095367432,
			slugs: {
				restaurant: 'california-burrito-malleshwaram-malleshwaram-2',
				city: 'bangalore',
			},
			cityState: '1',
			address: '"Saucepan Foodcourt, Orion Mall26 1, Bridage Gateway, Dr. Rajkumar Road, Bengaluru, Karnataka 560055"',
			locality: 'Malleshwaram',
			parentId: 1252,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 3900,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 3900,
				message: '',
				title: 'Delivery Charge',
				amount: '3900',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=7119514~p=16~eid=00000188-c912-02ab-0edf-cef1003d1007',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '4.4 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '20% OFF',
				subHeader: 'UPTO ₹50',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '41924',
				deliveryTime: 39,
				minDeliveryTime: 39,
				maxDeliveryTime: 39,
				lastMileTravel: 4.400000095367432,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.5',
			totalRatings: 5000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '288893',
			name: 'Meghana Foods',
			uuid: 'f0d470e8-1e64-473d-8af0-7745045daddb',
			city: '1',
			area: 'Rajajinagar',
			totalRatingsString: '10000+ ratings',
			cloudinaryImageId: 'slheenytwb3iaypqf4yd',
			cuisines: ['Biryani', 'Andhra', 'South Indian', 'North Indian', 'Chinese', 'Seafood'],
			tags: [],
			costForTwo: 50000,
			costForTwoString: '₹500 FOR TWO',
			deliveryTime: 27,
			minDeliveryTime: 27,
			maxDeliveryTime: 27,
			slaString: '27 MINS',
			lastMileTravel: 5,
			slugs: {
				restaurant: 'meghana-foods-rajajinagar-rajajinagar',
				city: 'bangalore',
			},
			cityState: '1',
			address: 'Unnati Arcade, Muncipal, No. 5/111 1st Main road, Rajkumar road, 1st block Rajajinagar ,Blr - 10',
			locality: 'Dr. Rajkumar Road',
			parentId: 635,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 5200,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 5200,
				message: '',
				title: 'Delivery Charge',
				amount: '5200',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '5 kms',
			hasSurge: false,
			sla: {
				restaurantId: '288893',
				deliveryTime: 27,
				minDeliveryTime: 27,
				maxDeliveryTime: 27,
				lastMileTravel: 5,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '4.4',
			totalRatings: 10000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '9607',
			name: "Brahmins' Thatte Idli",
			uuid: 'd6dd22fb-462a-4a73-8267-ba96e4b2368b',
			city: '1',
			area: 'Malleswaram',
			totalRatingsString: '10000+ ratings',
			cloudinaryImageId: 'cwajebccp1ylpr3ksx95',
			cuisines: ['South Indian'],
			tags: [],
			costForTwo: 15000,
			costForTwoString: '₹150 FOR TWO',
			deliveryTime: 22,
			minDeliveryTime: 22,
			maxDeliveryTime: 22,
			slaString: '22 MINS',
			lastMileTravel: 3.5,
			slugs: {
				restaurant: 'brahmins-thatte-idli-malleswaram-malleshwaram',
				city: 'bangalore',
			},
			cityState: '1',
			address: '#133/2-1, 8th main road, Below Neo dental care, ops to Dr srinivasan clinic, Malleshwaram, Bangalore-55',
			locality: '8th Main Road',
			parentId: 1312,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 3300,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 3300,
				message: '',
				title: 'Delivery Charge',
				amount: '3300',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=7124718~p=7~eid=00000188-c912-02ab-0edf-ceee003d076e',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.5 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '25% OFF',
				subHeader: 'UPTO ₹65',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '9607',
				deliveryTime: 22,
				minDeliveryTime: 22,
				maxDeliveryTime: 22,
				lastMileTravel: 3.5,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.5',
			totalRatings: 10000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '660508',
			name: 'Third Wave Coffee',
			uuid: 'df23a6e0-df03-48f6-8c76-48eef4ba9ac7',
			city: '1',
			area: 'Sahakar Nagar',
			totalRatingsString: '100+ ratings',
			cloudinaryImageId: '0dca660dbdf2e04f9b861c4426ffd41e',
			cuisines: ['Cafe', 'Beverages', 'Desserts'],
			tags: [],
			costForTwo: 40000,
			costForTwoString: '₹400 FOR TWO',
			deliveryTime: 28,
			minDeliveryTime: 28,
			maxDeliveryTime: 28,
			slaString: '28 MINS',
			lastMileTravel: 5.800000190734863,
			slugs: {
				restaurant: 'third-wave-coffee-sahakar-nagar-sahakar-nagar',
				city: 'bangalore',
			},
			cityState: '1',
			address: 'Thirdwave Coffee, No.864, Ground Floor, DBlock, Sahakar Nagar, Bangalore, Yelahanka ,B.B.M.P North, Karnataka-560092',
			locality: 'Yelahanka',
			parentId: 274773,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 5200,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 5200,
				message: '',
				title: 'Delivery Charge',
				amount: '5200',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=7102717~p=10~eid=00000188-c912-02ab-0edf-ceef003d0a16',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '5.8 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '30% OFF',
				subHeader: 'UPTO ₹75',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '660508',
				deliveryTime: 28,
				minDeliveryTime: 28,
				maxDeliveryTime: 28,
				lastMileTravel: 5.800000190734863,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.4',
			totalRatings: 100,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '10579',
			name: 'Pizza Hut',
			uuid: '70213aef-4308-461d-a5c8-6a25e0a51792',
			city: '1',
			area: 'New BEL Road',
			totalRatingsString: '10000+ ratings',
			cloudinaryImageId: '2b4f62d606d1b2bfba9ba9e5386fabb7',
			cuisines: ['Pizzas'],
			tags: [],
			costForTwo: 35000,
			costForTwoString: '₹350 FOR TWO',
			deliveryTime: 25,
			minDeliveryTime: 25,
			maxDeliveryTime: 25,
			slaString: '25 MINS',
			lastMileTravel: 1.899999976158142,
			slugs: {
				restaurant: 'pizza-hut-new-bel-road-sanjay-nagar-new-bel-road-yeshwanthpur',
				city: 'bangalore',
			},
			cityState: '1',
			address: '#3, OM Chambers, Ground Floor, New Bel Road, Devasandra, Opp Ramaiah Hospital',
			locality: 'New BEL Road',
			parentId: 721,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2700,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2700,
				message: '',
				title: 'Delivery Charge',
				amount: '2700',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1.8 kms',
			hasSurge: false,
			sla: {
				restaurantId: '10579',
				deliveryTime: 25,
				minDeliveryTime: 25,
				maxDeliveryTime: 25,
				lastMileTravel: 1.899999976158142,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.7',
			totalRatings: 10000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '556118',
			name: 'The Filter Coffee',
			uuid: 'e29f4071-650c-4c06-b56a-1dbb54306d86',
			city: '1',
			area: 'Sanjay Nagar',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'omptcztnc8roueqnjdhp',
			cuisines: ['South Indian'],
			tags: [],
			costForTwo: 25000,
			costForTwoString: '₹250 FOR TWO',
			deliveryTime: 26,
			minDeliveryTime: 26,
			maxDeliveryTime: 26,
			slaString: '26 MINS',
			lastMileTravel: 2.9000000953674316,
			slugs: {
				restaurant: 'the-filter-coffee-sanjay-nagar,-new-bel-road-sanjay-nagar,-new-bel-road',
				city: 'bangalore',
			},
			cityState: '1',
			address: 'NO. 1, PID No.019-M0021-21, 3rd Floor,KALPANA CHAWLA ROAD, BHOOPASANDRA, HEBBAL, BENGALURU, PIN 560 094',
			locality: 'Bhoopasandra',
			parentId: 21001,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2700,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2700,
				message: '',
				title: 'Delivery Charge',
				amount: '2700',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=7044192~p=13~eid=00000188-c912-02ab-0edf-cef0003d0d3f',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2.9 kms',
			hasSurge: false,
			sla: {
				restaurantId: '556118',
				deliveryTime: 26,
				minDeliveryTime: 26,
				maxDeliveryTime: 26,
				lastMileTravel: 2.9000000953674316,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.5',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '121702',
			name: 'Grill Biriyanis',
			uuid: '3fc303ac-0316-4d50-847a-477ef3684cf9',
			city: '1',
			area: 'Jalahalli  Peenya',
			totalRatingsString: '5000+ ratings',
			cloudinaryImageId: 'hdc4pzrx16smbsoozahv',
			cuisines: ['Biryani', 'Andhra', 'Tandoor', 'Grill'],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 27,
			minDeliveryTime: 27,
			maxDeliveryTime: 27,
			slaString: '27 MINS',
			lastMileTravel: 6.900000095367432,
			slugs: {
				restaurant: 'grill-biriyanis-jalahalli',
				city: 'bangalore',
			},
			cityState: '1',
			address: 'No 9, Near Jalahalli Metro Station, Jalahalli Cross, Bangalore - 57',
			locality: 'Jalahalli',
			parentId: 21649,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 5800,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 5800,
				message: '',
				title: 'Delivery Charge',
				amount: '5800',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '6.9 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '10% OFF',
				subHeader: 'ABOVE ₹800',
				discountTag: 'FLAT DEAL',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '121702',
				deliveryTime: 27,
				minDeliveryTime: 27,
				maxDeliveryTime: 27,
				lastMileTravel: 6.900000095367432,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '4.0',
			totalRatings: 5000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '23826',
			name: "Domino's Pizza",
			uuid: 'b8589a20-b4a4-45f0-b460-354a26c09217',
			city: '1',
			area: 'Yeshwanthpur',
			totalRatingsString: '10000+ ratings',
			cloudinaryImageId: 'sg9xutecl14q6qclvwsi',
			cuisines: ['Pizzas', 'Italian', 'Pastas', 'Desserts'],
			tags: [],
			costForTwo: 40000,
			costForTwoString: '₹400 FOR TWO',
			deliveryTime: 25,
			minDeliveryTime: 25,
			maxDeliveryTime: 25,
			slaString: '25 MINS',
			lastMileTravel: 0,
			slugs: {
				restaurant: 'dominos-pizza-mathikere-main-road-sanjay-nagar-new-bel-road-yeshwanthpur',
				city: 'bangalore',
			},
			cityState: '1',
			address: 'Mathikere Main Road, Bangalore Ground Floor, N0. 25/4, Mathikere Main Road (Next To Sangeetha Mobiles) Mathikere, Bangalore, Karnataka-560054',
			locality: 'Gokula 1st Stage',
			parentId: 2456,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2700,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2700,
				message: '',
				title: 'Delivery Charge',
				amount: '2700',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '₹100 OFF',
				subHeader: 'ABOVE ₹399',
				discountTag: 'FLAT DEAL',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '23826',
				deliveryTime: 25,
				minDeliveryTime: 25,
				maxDeliveryTime: 25,
				lastMileTravel: 0,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '4.3',
			totalRatings: 10000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '17300',
			name: 'KFC',
			uuid: '0a25f244-a1d2-49e6-8cb2-43047b1bc8fd',
			city: '1',
			area: 'New BEL Road',
			totalRatingsString: '10000+ ratings',
			cloudinaryImageId: '56c9ab92bd79745fd152a30fa2525426',
			cuisines: ['Burgers', 'Biryani', 'American', 'Snacks', 'Fast Food'],
			tags: [],
			costForTwo: 40000,
			costForTwoString: '₹400 FOR TWO',
			deliveryTime: 15,
			minDeliveryTime: 15,
			maxDeliveryTime: 15,
			slaString: '15 MINS',
			lastMileTravel: 1.399999976158142,
			slugs: {
				restaurant: 'kfc-new-bel-road-sanjay-nagar-new-bel-road-yeshwanthpur',
				city: 'bangalore',
			},
			cityState: '1',
			address: '#117 Shop No . 1,  AEGs Layout,  New BEL Road, Bengaluru - 560054',
			locality: 'AGS layout',
			parentId: 547,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2700,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2700,
				message: '',
				title: 'Delivery Charge',
				amount: '2700',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=7123588~p=22~eid=00000188-c912-02ab-0edf-cef3003d167a',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1.3 kms',
			hasSurge: false,
			sla: {
				restaurantId: '17300',
				deliveryTime: 15,
				minDeliveryTime: 15,
				maxDeliveryTime: 15,
				lastMileTravel: 1.399999976158142,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '3.9',
			totalRatings: 10000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '23699',
			name: "McDonald's",
			uuid: '11153e6a-6f1a-40a7-a99d-8682b47aca40',
			city: '1',
			area: 'New BEL Road',
			totalRatingsString: '10000+ ratings',
			cloudinaryImageId: 'ee5f8e06b300efc07c9fe3f4df40dfc4',
			cuisines: ['Burgers', 'Beverages', 'Cafe', 'Desserts'],
			tags: [],
			costForTwo: 40000,
			costForTwoString: '₹400 FOR TWO',
			deliveryTime: 16,
			minDeliveryTime: 16,
			maxDeliveryTime: 16,
			slaString: '16 MINS',
			lastMileTravel: 1.600000023841858,
			slugs: {
				restaurant: 'mc-donalds-sanjay-nagar-new-bel-road-yeshwanthpur-sanjay-nagar-new-bel-road-yeshwanthpur',
				city: 'bangalore',
			},
			cityState: '1',
			address: '215- Shashi Arcade, Near MS Ramaih Hospital, New BEL Road. Bengaluru -94',
			locality: 'Ms Ramaiah Nagar',
			parentId: 630,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2700,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2700,
				message: '',
				title: 'Delivery Charge',
				amount: '2700',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1.6 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: 'FREE ITEM',
				subHeader: '',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '23699',
				deliveryTime: 16,
				minDeliveryTime: 16,
				maxDeliveryTime: 16,
				lastMileTravel: 1.600000023841858,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '4.2',
			totalRatings: 10000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '349730',
			name: 'The Pizza Bakery',
			uuid: '5fc1f981-74ff-4d6f-a442-8c2795c1e75c',
			city: '1',
			area: 'Sanjay Nagar',
			totalRatingsString: '5000+ ratings',
			cloudinaryImageId: 'ilo4klvkknusv75nasq4',
			cuisines: ['Pizzas', 'Pastas', 'Italian', 'Desserts', 'Continental'],
			tags: [],
			costForTwo: 70000,
			costForTwoString: '₹700 FOR TWO',
			deliveryTime: 26,
			minDeliveryTime: 26,
			maxDeliveryTime: 26,
			slaString: '26 MINS',
			lastMileTravel: 2,
			slugs: {
				restaurant: 'the-pizza-bakery-sanjay-nagar,-new-bel-road-sanjay-nagar,-new-bel-road',
				city: 'bangalore',
			},
			cityState: '1',
			address: '#269, RMV 2ND STAGE, 2ND BLOCK, ARAMANE NAGAR, BANGALORE, Yeshwanthapura , B.B.M.P North, Karnataka-560094',
			locality: 'Aramane Nagar',
			parentId: 11108,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2700,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2700,
				message: '',
				title: 'Delivery Charge',
				amount: '2700',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=7137625~p=19~eid=00000188-c912-02ab-0edf-cef2003d1313',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '30% OFF',
				subHeader: 'UPTO ₹75',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '349730',
				deliveryTime: 26,
				minDeliveryTime: 26,
				maxDeliveryTime: 26,
				lastMileTravel: 2,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.3',
			totalRatings: 5000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '8167',
			name: 'Chai Point',
			uuid: '2d619d7f-f15b-4f35-a1b4-1e1224d46464',
			city: '1',
			area: 'Malleshwaram',
			totalRatingsString: '10000+ ratings',
			cloudinaryImageId: 'lfyrq6ip6cnrupwbzqua',
			cuisines: [
				'Bakery',
				'Beverages',
				'Maharashtrian',
				'Snacks',
				'Street Food',
				'South Indian',
				'Punjabi',
				'Chaat',
				'Indian',
				'American',
				'North Indian',
				'Fast Food',
				'Desserts',
				'Cafe',
				'Healthy Food',
				'Home Food',
			],
			tags: [],
			costForTwo: 15000,
			costForTwoString: '₹150 FOR TWO',
			deliveryTime: 32,
			minDeliveryTime: 32,
			maxDeliveryTime: 32,
			slaString: '32 MINS',
			lastMileTravel: 4.199999809265137,
			slugs: {
				restaurant: 'chai-point-18th-cross-road-malleshwaram',
				city: 'bangalore',
			},
			cityState: '1',
			address: 'Chai Point, 18th Cross Road, Malleswaram, Bangalore, Karnataka',
			locality: '18th Cross Road',
			parentId: 1607,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 3900,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 3900,
				message: '',
				title: 'Delivery Charge',
				amount: '3900',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=7127357~p=25~eid=00000188-c912-02ab-0edf-cef4003d195f',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '4.1 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '40% OFF',
				subHeader: 'UPTO ₹80',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '8167',
				deliveryTime: 32,
				minDeliveryTime: 32,
				maxDeliveryTime: 32,
				lastMileTravel: 4.199999809265137,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.6',
			totalRatings: 10000,
			new: false,
		},
		subtype: 'basic',
	},
];

// menu items api card type key
export const MENU_ITEM_TYPE_KEY = 'type.googleapis.com/swiggy.presentation.food.v2.ItemCategory';
export const RESTAURANT_TYPE_KEY = 'type.googleapis.com/swiggy.presentation.food.v2.Restaurant';

export const ITEM_IMG_CDN_URL = 'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/';

// Image CDN URL for Restaurant card
export const IMG_CDN_URL = 'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/';

// shimmer card unit
export const shimmer_card_unit = 8;

// shimmer Menu card unit
export const shimmer_menu_card_unit = 4;

// Swiggy API to get Restaurant data with corsproxy
export const swiggy_api_URL =
	'https://corsproxy.io/?https://www.swiggy.com/dapi/restaurants/list/v5?lat=13.035280822533668&lng=77.55963755857057&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING';

// Swiggy API to get Restaurant Menu data with corsproxy
export const swiggy_menu_api_URL =
	'https://corsproxy.io/?https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=21.1702401&lng=72.83106070000001&&submitAction=ENTER&restaurantId=';
